version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: sikaltara_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sikaltara_db
      POSTGRES_USER: sikaltara
      POSTGRES_PASSWORD: sikaltara2024
    ports:
      - "5432:5432"
    volumes:
      - sikaltara_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sikaltara -d sikaltara_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sikaltara_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - sikaltara_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sikaltara_pgdata:
  sikaltara_redisdata:
